[tool.black]
line-length = 150
#exclude = ["versioneer.py", "visual_check.py"]
## exclude = "\.pyi?$" #extend-exclude = '''.*test_.*'''

[tool.ruff]
lint.select = [
    "E",    # pycodestyle Error
    "F",    # Pyflakes
    "I",    # isort
    "Q",    # flake8-quotes
    "W",    # pycodestyle Warning
    "C90",  # mccabe
]
fix = true
lint.ignore = ["C901", "E714", "I001"]
exclude = [".venv", ".ipynb", "versioneer.py", "*_cache"]
line-length = 150  # Same as Black

# [tool.ruff.lint]  default ruff config, equaivalent to Black default config
# select = ["E4", "E7", "E9", "F"] # default: https://docs.astral.sh/ruff/configuration/
# ignore = []
# Allow fix for all enabled rules (when `--fix`) is provided.
# fixable = ["ALL"] # default
# unfixable = []

# [tool.ruff.format] # default ruff config, equaivalent to Black default config
# quote-style = "double"
#indent-style = "space"
# skip-magic-trailing-comma = false
# line-ending = "auto"



