name: pre-commit (linter, formatter)
on: [ push, pull_request ]
jobs:
  pre-commit:
    runs-on: ubuntu-latest  # TODO test also for windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: pre-commit/action@v3.0.1
      - name: Setup pre-commit
        # Don't need "pre-commit install --install-hooks" since we're just interested in running the hooks.
        run: |
          pre-commit install-hooks

      - name: Run pre-commit only on files which have changed
        run: |
          pre-commit run
